export const mapas = [
    {
        id: 'space',
        nome: 'SPACE',
        descricao: 'Arena no vazio do espaço',
        corCSS: '#00cfff',
        corFundo: 0x000008,
        corGrid1: 0x00cfff,
        corGrid2: 0x003366,
        corChao: 0x000011,
        corParede: 0x00cfff,
        emissividadeParede: 1.4,
        opacidadeParede: 0.20,
        mostrarGrid: true,
        mostrarStars: true,
        temFog: false,
        luzAmbiente: 0x111233,
    },
    {
        id: 'deserto',
        nome: 'DESERT',
        descricao: 'Arena nas areias do deserto',
        corCSS: '#c8a060',
        corFundo: 0xD2956C,
        corGrid1: 0x8b6914,
        corGrid2: 0x3d2a00,
        corChao: 0x8b6914,
        corParede: 0xc8a060,
        emissividadeParede: 0.0,
        opacidadeParede: 1.0,
        mostrarGrid: false,
        temFog: true,
        corFog: 0xD2956C,
        fogNear: 30,
        fogFar: 90,
        luzAmbiente: 0x4a3010,
        texturas: {
            diffuse: './textures/areia/sandy_gravel_diff_2k.jpg',
            normal:  './textures/areia/sandy_gravel_nor_gl_2k.jpg',
            rough:   './textures/areia/sandy_gravel_rough_2k.jpg',
        },
        corNeonMota: 0xffff00
    },
    {
        id: 'jungle',
        nome: 'JUNGLE',
        descricao: 'Arena na floresta densa',
        corCSS: '#22cc44',
        corFundo: 0x010a02,
        corGrid1: 0x22cc44,
        corGrid2: 0x0a2a0a,
        corChao: 0x0a1a08,
        corParede: 0x1a3d0a,
        emissividadeParede: 0.0,
        opacidadeParede: 1.0,
        mostrarGrid: false,
        temFog: true,
        corFog: 0x0a1f08,
        fogNear: 20,
        fogFar: 70,
        luzAmbiente: 0x0a2010,
        texturas: {
            diffuse: './textures/jungle/rocky_terrain_02_diff_2k.jpg',
            normal:  './textures/jungle/rocky_terrain_02_nor_gl_2k.jpg',
            rough:   './textures/jungle/rocky_terrain_02_rough_2k.jpg',
        }
    },
    {
        id: 'gelo',
        nome: 'ICE',
        descricao: 'Arena glaciar no ártico noturno',
        corCSS: '#66ddff',
        corFundo: 0x040c18,       // azul noite ártico profundo
        corGrid1: 0x66ddff,
        corGrid2: 0x113355,
        corChao: 0xaaccee,
        corParede: 0x99ccff,
        emissividadeParede: 0.0,
        opacidadeParede: 1.0,
        mostrarGrid: false,
        temFog: true,
        corFog: 0x040c18,
        fogNear: 30,
        fogFar: 80,
        luzAmbiente: 0x040c18,
        texturas: {
            diffuse: './textures/gelo/snow_02_diff_2k.jpg',
            normal:  './textures/gelo/snow_02_nor_gl_2k.jpg',
            rough:   './textures/gelo/snow_02_rough_2k.jpg',
        }
    }
];
